### PR TITLE
Refactor

### PR DESCRIPTION
**Pull request by eemeli**
This builds on top of #19.

The code refactoring is pretty minor, but two new features are added:
- `getRules()` provides predefined parser rules. These have been extracted from [Pontoon](https://github.com/mozilla/pontoon/tree/master/translate/src/core/placeable) and modified to fit the structure here.
- `createMarker()` gets a second optional argument `wrapTag`, which lets users define the wrapper they want to use. This will let e.g. Pontoon add the `<Localized>` wrappers to these that it uses.

All of the included rules mark their matching content with a `<mark data-mark="...">`, where the data field includes a unique identifier for that rule. When the match is not included directly as its child, it is included as the value of a `data-match` attribute.

### CODE REVIEW

**Comment by eemeli** [comment]
A package built from commit ce3c1fe is available on npm under the `next` dist-tag as `react-content-marker@2.2.0-1`.

**Comment by mathjazz** [comment]
Could you rebase, pretty please?

I'm curios what's the motivation for these changes, in particular for moving the rules to the library. Is that related to the data model PR?

**Comment by eemeli** [comment]
Rebased. Had rather hoped that GitHub would've picked up on the smaller diff once the parent PR was merged.

The motivation for this change has three different aspects:
1. Establishing a clearer separation of concerns. By including the rules here, the marker component becomes simultaneous much richer and simpler from a user's PoV: we only need to say if we'd like the rules to include Fluent & leading-spaces support, and don't need to provide the whole library of rules to make that happen in the first place.
2. Enabling multiple users to share the same rules. We already publish this as a separate component, so by including the rules here we're making it potentially more interesting for others to use as well, either internally at Mozilla or externally. More users; more eyeballs; more bugs found.
3. Help clarify the markup API so that data model changes in Pontoon are more straightforward. I've a dependent change in Pontoon ([d0f306a1](https://github.com/eemeli/pontoon/commit/d0f306a180a09f1edb010a3d181c08ca463d434d), PR available soon) which refactors all of the `<WithPlaceables*>` components and `getMarker()` calls into one place, so that if/when the data model needs to represent a message as a structure rather than a flat string, only that place needs to change for this markup.

**Review by mathjazz — APPROVED** [review]
Thanks for clarifying. Looks good!

**Pull request merged**
